### ISSUE TITLE
Using LambdaLogger.Log for writting in cloudwatch doesn't work

### ISSUE THREAD

**Issue by pablocastilla** [localstack-dotnet/localstack-dotnet-client#8] opened 2021-04-12 12:35 UTC
I am trying to write into cloudwatch using LambdaLogger.Log("text"); into a asp.net core that will be executed in a lambda.

I have set the services:

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();

            services.AddLocalStack(Configuration);
            services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
            services.AddAwsService<Amazon.CloudWatchLogs.IAmazonCloudWatchLogs>();

        }

## Expected Behavior
When I use LambdaLogger.Log("text"); in the controller I expect to see an entry in cloudwatch

## Actual Behavior
Nothing is written

## Steps to Reproduce the Problem

  1.Create an asp.net core app that will be executed in a lambda
  2.Set the services configuration
  3.Use LambdaLogger.Log("text")

## Specifications

  - Version: 1.1.0
  - Platform: windows
  - Subsystem: asp.net core 3.1

Thanks

**Comment by Blind-Striker** [comment] 2021-05-24 11:08
Hi @pablocastilla,

I'm not sure this issue caused by this client library.  Please check this issue https://github.com/localstack/localstack/issues/1394, it might be related to your problem. 

Please inform me after, I can do more in-depth tests or move this issue to the [LocalStack](https://github.com/localstack/localstack) repo.

**Comment by Blind-Striker** [comment] 2021-06-01 12:04
Hi @pablocastilla, closing this issue, please try the new version. If the problem still continues you can re-open the issue.

**Closed by Blind-Striker** 2021-06-01 12:04 UTC
Labels: potential bug
